name: prepvault_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.5.5+11

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  confetti: ^0.7.0
  flutter_slidable: ^4.0.3

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Backend & Navigation
  supabase_flutter: ^2.10.3
  go_router: ^17.0.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  # File Handling & Media
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^31.2.16
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  
  # AI & Features
  google_mlkit_text_recognition: ^0.15.0
  flutter_markdown: ^0.7.7+1
  speech_to_text: ^7.3.0
  
  # Utils
  lottie: ^3.3.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  in_app_purchase: ^3.2.3
  timeago: ^3.7.1
  http: ^1.6.0
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  fl_chart: ^1.1.1
  google_mobile_ads: ^6.0.0
  smooth_page_indicator: ^2.0.1
  country_picker: ^2.0.27
  in_app_purchase_android: ^0.4.0+8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  
  # Icon Generator
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # üëá SPLASH SCREEN GENERATOR ADDED
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png # üëà Ensure ye file majood ho
    - assets/icon/icon.png 
    - assets/animations/

# --- CONFIGURATIONS ---

# 1. Launcher Icon Config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

# 2. üëá Native Splash Screen Config (Ye White Screen Hatayega)
flutter_native_splash:
  # Ye wo color hai jo white screen ko cover karega (Deep Blue)
  color: "#1a237e"
  
  # ‚ùå Image lines ko hata diya ya comment kar diya
  # image: assets/logo.png 
  
  fullscreen: true

  # Android 12+ ke liye settings
  android_12:
    color: "#1a237e"